version: '3.8'

services:
  cli:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hydra-moe:local
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    entrypoint: ["tini", "--", "bash", "./docker/run.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hydra-moe:local
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    entrypoint: ["tini", "--", "bash", "./docker/run_webui.sh"]
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8001:8001"
    
  api_server:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: hydramoe_api:local
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    entrypoint: ["tini", "--", "bash", "./run.sh"]
    volumes:
      - .:/code
    networks:
      - hydra-moe_default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"

networks:
  hydra-moe_default:
    external: true
