version: '3.8'

services:
  api_server:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: hydramoe_api2:local2
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    entrypoint: ["tini", "--", "bash", "./run.sh"]
    volumes:
      - ./api:/code
    networks:
      - hydra-moe_default2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "443:443"


networks:
  hydra-moe_default2:
    external: false
